name: Publish image
on:
  pull_request:
    types:
      - closed
    paths:
      - Dockerfile

jobs:
  publish:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Get parent image tag
        id: tag
        run: |
          echo "TAG_NAME=$(awk '/^FROM ghcr.io\/kanisterio\/kanister-tools/ {print $NF}' Dockerfile | sed 's/^.*://g')" >> $GITHUB_OUTPUT
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kanister-kubectl-1.27
          tags: latest ${{ steps.tag.outputs.TAG_NAME }}
          containerfiles: |
            ./Dockerfile
      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
